package dev.pocketportal.app

object AppConstants {
    const val DEFAULT_CONFIG_RESOURCE = "pocketportal.properties"
    const val CONFIG_PATH_ENVIRONMENT_VARIABLE = "POCKETPORTAL_CONFIG"
    const val XDG_CONFIG_HOME_ENVIRONMENT_VARIABLE = "XDG_CONFIG_HOME"
    const val HOME_ENVIRONMENT_VARIABLE = "HOME"
    const val USER_CONFIG_RELATIVE_PATH = ".config/pocketportal/pocketportal.properties"
    const val XDG_CONFIG_RELATIVE_PATH = "pocketportal/pocketportal.properties"
    const val HOST_ENVIRONMENT_VARIABLE = "POCKETPORTAL_HOST"
    const val PORT_ENVIRONMENT_VARIABLE = "POCKETPORTAL_PORT"
    const val HOST_PROPERTY = "server.host"
    const val PORT_PROPERTY = "server.port"
    const val ADB_PATH_ENVIRONMENT_VARIABLE = "POCKETPORTAL_ADB_PATH"
    const val ADB_TIMEOUT_ENVIRONMENT_VARIABLE = "POCKETPORTAL_ADB_TIMEOUT_MILLIS"
    const val ADB_PATH_PROPERTY = "android.adb.path"
    const val ADB_TIMEOUT_PROPERTY = "android.adb.timeoutMillis"
    const val SCREENSHOT_MAXIMUM_BYTES_ENVIRONMENT_VARIABLE =
        "POCKETPORTAL_SCREENSHOT_MAXIMUM_BYTES"
    const val SCREENSHOT_MAXIMUM_BYTES_PROPERTY = "android.screenshot.maximumBytes"
    const val DEFAULT_SCREENSHOT_MAXIMUM_BYTES = 8_388_608L
    const val ADB_BRIDGE_ENABLED_PROPERTY = "android.bridge.enabled"
    const val ADB_BRIDGE_ENABLED_ENVIRONMENT_VARIABLE = "POCKETPORTAL_ADB_BRIDGE_ENABLED"
    const val ADB_BRIDGE_TOKEN_ENVIRONMENT_VARIABLE = "POCKETPORTAL_ADB_BRIDGE_TOKEN"
    const val TRUE_VALUE = "true"
    const val FALSE_VALUE = "false"
    const val MINIMUM_ADB_BRIDGE_TOKEN_CHARACTERS = 32
    const val TLS_ENABLED_PROPERTY = "server.tls.enabled"
    const val TLS_PORT_PROPERTY = "server.tls.port"
    const val TLS_HOST_PROPERTY = "server.tls.host"
    const val TLS_KEY_STORE_PATH_PROPERTY = "server.tls.keyStorePath"
    const val TLS_KEY_ALIAS_PROPERTY = "server.tls.keyAlias"
    const val TLS_ENABLED_ENVIRONMENT_VARIABLE = "POCKETPORTAL_TLS_ENABLED"
    const val TLS_PORT_ENVIRONMENT_VARIABLE = "POCKETPORTAL_TLS_PORT"
    const val TLS_HOST_ENVIRONMENT_VARIABLE = "POCKETPORTAL_TLS_HOST"
    const val TLS_KEY_STORE_PATH_ENVIRONMENT_VARIABLE = "POCKETPORTAL_TLS_KEY_STORE_PATH"
    const val TLS_KEY_ALIAS_ENVIRONMENT_VARIABLE = "POCKETPORTAL_TLS_KEY_ALIAS"
    const val TLS_KEY_STORE_PASSWORD_ENVIRONMENT_VARIABLE =
        "POCKETPORTAL_TLS_KEY_STORE_PASSWORD"
    const val TLS_PRIVATE_KEY_PASSWORD_ENVIRONMENT_VARIABLE =
        "POCKETPORTAL_TLS_PRIVATE_KEY_PASSWORD"
    const val DEFAULT_TLS_PORT = 8443
    const val DEFAULT_TLS_KEY_ALIAS = "pocketportal"
}
